### ISSUE TITLE
Javscript error during install

### ISSUE THREAD

**Issue by TMirabel** [owlbear-rodeo/kenku-fm#107]
**Describe the bug**
After starting installation, error message occurs. 

**To Reproduce**
doubleclick to install exe

**Expected behavior**
Error message during install of the file. 

**Screenshots**
![image](https://github.com/owlbear-rodeo/kenku-fm/assets/149206582/4bb923a3-d411-4c92-bdb2-531716f5f7a0)

**Desktop (please complete the following information):**
Windows 10 Home

**Additional context**

**Comment by nthouliss** [comment]
I cannot reproduce this error. If someone else comes across it feel free to reopen
