### ISSUE TITLE
Auto Skipping Spotify Songs

### ISSUE THREAD

**Issue by EonofAeon** [owlbear-rodeo/kenku-fm#110]
**Describe the bug**
When attempting to play songs through the spotify web player within Kenku, it will auto skip a varying number of valid songs before landing on one to play, whether it is a personal playlist or random 'radio' option or even a singular song.

**To Reproduce**
1. Open the Spotify Web/App player connection within Kenku
2. Select a song and/or playlist.
3. Tell it to start playing
4. It proceeds to skip songs initially.

**Expected behavior**
I expected it to play the marked songs, as they are all songs and playlists that function normally and without issue on the Windows Spotify App on my PC.

**Desktop (please complete the following information):**
1.4.1 on Desktop

**Comment by colettak** [comment]
This is happening on 1.4.0 as well, reminds of the issue that happened before with spotify.

**Comment by jakeabetes** [comment]
I ran into this and found a solution https://github.com/owlbear-rodeo/kenku-fm/issues/117
