### ISSUE TITLE
Add Zoom to Browser Tabs

### ISSUE THREAD

**Issue by SoraDevin** [owlbear-rodeo/kenku-fm#25]
Some interfaces (Like Spotify) are a little difficult to work with because they are so zoomed in. Being able to adjust this like in a normal browser would be very useful.

**Comment by mitchemmc** [comment]
To support this we'd need to add a lot of little things (per tab zoom levels, persisted zoom levels, menu items, shortcus) so it's a bit too much work compared to the benefits it would provide for us right now.
