### ISSUE TITLE
Enhancement - Ability to export playlists and soundboards

### ISSUE THREAD

**Issue by r-valyar** [owlbear-rodeo/kenku-fm#26]
This is not a bug request but feature enhancement suggestion. In short - **provide ability to export one or more playlists and soundboards.**

This will facilitate situations where OS or application has to be reinstalled with clean config or when there are more than one machines. For example I have Windows and macOS computers and keeping the two instances in synchronization on playlist/soundboard level will be perfect.

**Comment by mitchemmc** [comment]
We don’t copy any songs you import into Kenku FM instead we just store the location on your hard drive to play. This means that exporting wouldn’t work because if we imported the playlist on a new computer the songs wouldn’t be in the same place on the hard drive so playback would fail.

**Comment by r-valyar** [comment]
Yes, I know you are storing the location and I believe an export functionality will be quite welcomed in cases where people are using network location (as I do) for their files Network location will be the same. 

Also export/import for backup purposes is also a use case.

**Comment by mitchemmc** [comment]
The majority of our users use it for playback of local files, and would expect that any official import/export feature would work accross devices (as this is the most common use case for the feature).
So if we we're to add the feature then it would lead to a bad user experience as it would not work how the majority of users would expect.

Until we can dedicate time to implement this in a way that it would work in all cases then it is not something we're planning.

**Comment by mitchemmc** [comment]
Thinking more on this, although this is not officially supported you could copy the local database to the new computer to get the result you're looking for.

The database location for Kenku FM is here on Windows:
`%appdata%\Roaming\Kenku FM\Local Storage`
and here on Mac:
`~/Library/Application Support/Kenku FM/Local Storage`
