### ISSUE TITLE
[UX Issue] - Missing name when adding track

### ISSUE THREAD

**Issue by m4rcLs** [owlbear-rodeo/kenku-fm#27]
**Describe the bug**
First off I totally understand your contribution policy and I'm not 100 % sure if this can be classified as a bug but for me it is an inconvenience.

When adding a track, most of the time you will have an URL ending with a file name.
This file name is not applied to the name field.

**To Reproduce**
1. Open any Playlist or Soundboard
2. Add track
3. Choose or Drag'n'Drop a file

**Expected behavior**

From a user standpoint I would expect the name of the file to be automatically filled into the name field below.  
Optionally without the file ending.
This would make it so much easier to simply drag in a file and add it.

**Screenshots**
**Is**
<img src="https://user-images.githubusercontent.com/31926457/161413494-7a93137f-f0f5-4497-8a31-edf26976a966.png" width="500px"/>
**Expected**
<img src="https://user-images.githubusercontent.com/31926457/161413508-4ee6ced8-dc58-44a4-ae70-567370927d30.png" width="500px"/>

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.0.0

**Additional context**

**Comment by mitchemmc** [comment]
For files I recommend using our drag and drop support as shown here https://www.kenku.fm/docs/using-kenku-player
this supports adding multiple files at once as well as automatically filling in their names.

Saying this I think their should be parity between the two features so I will look into this in the future.
However as there is a better alternative this is a low priority and may not be addressed for a while.

**Comment by m4rcLs** [comment]
Totally understable, it is only a minor inconvenience for me :)
