### ISSUE TITLE
Discord Bot Playback Intermediate Stuttering

### ISSUE THREAD

**Issue by SoraDevin** [owlbear-rodeo/kenku-fm#31]
**Describe the bug**
When the discord bot is playing back music occasionally this audio will stutter, giving a disjointed listening experience.

**To Reproduce**
Set up the bot as per instructions. I encountered this error the most when I was playing a long (1+ hr) audio track I had imported from my local machine into a playlist/soundboard and was streaming a spotify song on top of it. The stuttering was mostly noticeable because the long track was ambience with a lot of consistent, repetitive sounds in it.

**Expected behavior**
Smooth playback with no noticeable stuttering

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Was on a high end network, but was running kenku and discord on the same laptop and getting moderate levels of memory usage (still flash tho, no swp/paging). Also had the multi-out feature on with only discord bot as the output

**Comment by nthouliss** [comment]
Could you confirm if this is still an issue with v1.1.0? There has been a targeted effort at performance improvements in that update.

**Comment by SoraDevin** [comment]
I'll test when I get home and update

**Comment by SoraDevin** [comment]
It's still present when using discord on my laptop, I think about the same. There could be a problem with either discord or my audio drivers, the sound appears ok when I use discord on my phone. Interestingly Kenku is using my GPU which I was not expecting. The discord server is in singapore currently due to having a player overseas btw. Inconclusive at this point.

I'll test it with all my players in our next session and see if they still get any stuttering on their ends.

**Comment by SoraDevin** [comment]
Also if I try connecting to a bluetooth speaker to play through my laptop the stuttering becomes really terrible

**Comment by nthouliss** [comment]
If you have the latest version of Kenku FM then I'd take a look at what other programs you're running. We did a lot of optimisations but the stuttering can sometimes be caused by the CPU throttling (for instance, when you tested it through your phone, was the Discord on you laptop closed? It could have freed up resources). I'd also make sure any other audio apps are closed (unless you're using it via virtual cable)

Bluetooth can switch to lower audio codecs on some systems but it's not recommended to use any sort of Bluetooth with Kenku FM.

**Comment by SoraDevin** [comment]
Will take a look again tomorrow. Have got an in-person session so will be able to better compare with lower cpu load. Out of curiosity would it not be beneficial to implement a small buffer (~200ms) instead of trying to make throughput realtime?

**Comment by nthouliss** [comment]
There is a buffer, it's size changes depending on what mode you're in (i.e. low latency mode vs performance mode)

**Comment by SoraDevin** [comment]
Can confirm that performance was much better running on discord with laptop running the application and desktop using the audio for the whole room. Wasn't aware we could change modes though?

**Comment by nthouliss** [comment]
> Wasn't aware we could change modes though?

This was a change in 1.1.0 :)
