### ISSUE TITLE
[Bug] Window size is not retained between program launches. 

### ISSUE THREAD

**Issue by r-valyar** [owlbear-rodeo/kenku-fm#33]
**Describe the bug**
Kenku FM window size is not retained when program is restarted. Every time I launch it, the window is same small size and I have adjust it. 

**To Reproduce**
1. Launch Kenku FM
2. Maximize or adjust the window size
3. Close the program
4. Start it. Window will be reset to its original size.

**Expected behavior**
The window size (and position) should be retained between application launched. 

**Screenshots**
![image](https://user-images.githubusercontent.com/63558984/162563100-c22bc02a-1a3b-471a-8570-43295b2eb3ce.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, 20H2
 -  macOS Monterey 12.3.1

**Additional context**
n/a

**Comment by r-valyar** [comment]
This bug report is also valid for macOS:

- Mac mini (M1, 2020), Monterey 12.3.1

**Comment by nthouliss** [comment]
We'll have a look into this, but it could take a little while. Kenku FM is an Electron App and while this seems like it should be a solved thing, it's definitely not:

https://github.com/electron/electron/issues/526

**Comment by jbhaywood** [comment]
+1 to this. I have to resize the window every time it launches. The issue posted above lists a number of workarounds, so I hope Kenku isn't waiting for Electron to fix it on their end.
