### ISSUE TITLE
[Feature] Add Youtube URLs to playlists

### ISSUE THREAD

**Issue by NicEastvillage** [owlbear-rodeo/kenku-fm#35]
Greetings. I understand, that you do not accept PRs with features, so I want to inquire if this feature is on the roadmap.

Kenku FM currently allows you to make playlists of local audio, but you can also make bookmarks to sites like Youtube from which it can play audio/video. I would love to have the intersection of these two, i.e. to be able to make playlists with Youtube videos -- ideally a mix of local audio and Youtube videos. The local audio would be played as currently while Youtube video would use the browser feature.

Afaik, most of the *groundwork* for this feature is already implemented due to existing features. However, I can imaging several challenges with design, UI, the mixing of playlists and browsers, Youtube's ToS, etc, so I understand if this feature is off the table.

Allowing a mix of local and online sources in playlists would open up a lot of freedom. My current alternative is to make playlists on Youtube and make a bookmark for each of those, but I don't have the nice UI of playlists and have to find online versions of local tracks.

**Comment by mitchemmc** [comment]
This isn't a feature we're considering as we would need to use something like youtube-dl to get the raw audio stream for the input. This would mean we would break YouTube ToS by bypassing ads. The App was very consciously designed the way it is to keep external services in their natural state to avoid any issues with takedowns and such.
