### ISSUE TITLE
[Feature] Icecast output

### ISSUE THREAD

**Issue by pgmillon** [owlbear-rodeo/kenku-fm#40]
While discord output is already great, it would be ever greater if we could output to a running icecast server.
Such feature would allow to have music directly in vtt soft like foundry where a simple audio element on the canva can be used to broadcast icecast audio.
With such setup, no additional bot, no discord limitations and pure vtt immersion.
Thanks for considering this request.

**Comment by pgmillon** [comment]
https://www.chrisjmendez.com/2017/06/12/how-to-publish-an-mp3-to-icecast-using-nodejs-part-2-of-2/

**Comment by nthouliss** [comment]
We had a look into Icecast but we can't use it as it doesn't support MacOS. However, we do have plans to support other outputs besides Discord but that's a longer term goal.
