### ISSUE TITLE
[Question] Difference between "Low Latency" and "Performance" modes under Streaming section

### ISSUE THREAD

**Issue by r-valyar** [owlbear-rodeo/kenku-fm#58]
I don't find the answer in the documentation and I don't use reddit, therefore I place my question here:
- What is the difference between the two modes under Performance category?
![image](https://user-images.githubusercontent.com/63558984/205851147-7d7d4b5e-866b-4d82-92f7-ae560187862a.png)

**Comment by r-valyar** [comment]
Anyone? :(

**Comment by nthouliss** [comment]
The streaming mode determines the size of the audio streaming buffer

https://github.com/owlbear-rodeo/kenku-fm/blob/051666abc0ef7382654a4a40b927518958cd0ff9/src/preload/managers/AudioCaptureManagerPreload.ts#L82-L85

**Comment by r-valyar** [comment]
Thanks. Clear now.
