### ISSUE TITLE
Kenku stops playing after ~43 seconds

### ISSUE THREAD

**Issue by Voidchimera** [owlbear-rodeo/kenku-fm#70]
**Describe the bug**
I opened Kenku today for a session, but the music would stop playing through discord after ~43 seconds or so. The only way to make it work again is to change the voice channel it's connected to, and then going back to the one you want it to play music in. It's as if it had some sort of timer.

This happens with both music streamed from YouTube or files from my computer.

**To Reproduce**
I'm unsure how to reproduce it. It may as well be just a particular case.
1. Open Kenku and connect it to a Discord voice channel
2. Stream music, either from a YouTube video or a file from your computer
3. After ~43 seconds, the bot will stop playing music until you switch voice channels.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
The program was working perfectly yesterday; it stopped working correctly today. Tried restarting too.
I tried changing the bot's token, but it didn't fix it.

**Comment by nthouliss** [comment]
We released a temporary fix for this in v1.2.4. There's some regression for audio but at least there's no disconnection. We're waiting on an official patch in the Discord.JS library.

**Comment by mthehh** [comment]
Hi, how do I apply that hotfix?

**Comment by nthouliss** [comment]
@mthehh You don't need to do much. Just close your Kenku FM, wait about 2 minutes and then close it again. When you open it again it should be updated, you can check in the settings (the gear icon at the top) that it's v1.2.4 (it'll be at the bottom in the settings)

**Comment by nthouliss** [comment]
@mthehh I realised that my instructions weren't exactly clear, you have to close Kenku FM, open it, wait 2 minutes, close and then open again. Then do the checks through the settings to make sure it's applied. 

Or you can just go an download the latest from https://www.kenku.fm/download
