### ISSUE TITLE
Bot randomly stops playing music

### ISSUE THREAD

**Issue by pichuknight** [owlbear-rodeo/kenku-fm#74]
I just set up the bot and it worked perfectly during out first session, going into the second session and the bot just randomly stops playing now? On both downloaded music and the browser it will just stop playing for some reason. Having it leave the voice channel and reconnect seems to let it keep playing. The music does not pause, the sound just stops playing but I can see it still progressing through the track.

**Comment by jan-polivka** [comment]
This probably won't help but if you pull and roll back to the previous commit, 9f6f9df4fb3a1812a911a2989bdb6beb68746c50 (origin/release/v1.2.4), it should work.

**Comment by jan-polivka** [comment]
I tested the previous commit as mentioned and I tested the newest commit, both in development mode and they seem to work just fine. The production build dies almost immediately when I play a YouTube playlist.

**Comment by pichuknight** [comment]
I will give that a try then, thank you for looking into it.

**Comment by jan-polivka** [comment]
Looked into it some more. The issue appears on v1.2.2. I am not sure about 1.2.3 but the issue seems to be fixed on v1.2.4.  I tried both versions with development mode and so that's my conclusion.

Anyway, if you download a fresh copy from the website, it will be v1.2.4.

**Comment by binarybandit03** [comment]
I am still having this issue on v1.2.4. 
When I am not in the same room as the bot, it works fine. But then when I join, it usually lasts for about 1 min the first time, then about 30 seconds thereafter.
I attempted to uninstall the app, and then re-install it, but all of the settings are still the same. I don't think that has any effect on it, but wasn't sure if redeploying the bot or something may have been able to help. (I have not done that yet as I mentioned the token and other settings remained stored) I haven't gone looking for the programdata/appdata to clear it out either.
Tried different latencies, tried to disable the remote, disconnect and reconnect the bot. 
Happens with Spotify as of right now. 
Standard player (uploaded files) works just fine.
Youtube seems to work as well.

**Comment by Shaydee1990** [comment]
I noticed this issue too today after using the program since Friday. Suddenly it stopped playing music through my discord. I tried rolling back to v1.2.3 but it worked for a minute before stopping again. I've tried every fix I've read here without anything fixing it. Though I am somewhat glad I'm not the only one with this issue!

**Comment by AdamSturge** [comment]
Also have this issue on 1.2.4.

**Comment by nthouliss** [comment]
Could ya'll check that 1.3.1 resolves this for you?

**Comment by Shaydee1990** [comment]
> Could ya'll check that 1.3.1 resolves this for you?

So far so good :)

**Comment by AdamSturge** [comment]
How does one downgrade the client app? Is there a link to older installers?
