### ISSUE TITLE
Error connecting to bot: creating the TLS connector resulted in a error

### ISSUE THREAD

**Issue by CodyNguyen235** [owlbear-rodeo/kenku-fm#77]
**Describe the bug**
When trying to connect Kenku-FM to discord, I get the error: "Error connecting to bot: creating the TLS connector resulted in a error"

**To Reproduce**
1. Input Discord Token
2. Click on 'Connect'

**Expected behavior**
Connects to discord to be able to play music. 

**Screenshots**
![image](https://user-images.githubusercontent.com/65568860/226551821-3b97e7eb-959e-4a0c-abf7-06055a0ce106.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.3.0

**Additional context**
Note that Kenku-fm 1.2.4 is able to connect to discord but no sound comes from the bot.

**Comment by nthouliss** [comment]
I went ahead and created a pre-release with the app packaged, just in case. 

https://github.com/owlbear-rodeo/kenku-fm/releases/tag/v1.3.1-test

Let me know if it works. It isn't production-level but if it resolves your issue, I'll start working on making a new version.

**Comment by QaisQaisQais** [comment]
I am having the same issue

**Comment by QaisQaisQais** [comment]
your fix didn't work for me for some reason

**Comment by CodyNguyen235** [comment]
I tried the new version and unfortunately did not see any difference. Did you increase the version number? It still says 1.3.0, but i am sure i downloaded the pre-release. 

![image](https://user-images.githubusercontent.com/65568860/226707952-589dc6cc-d58c-48cb-a4e4-0528f42abd33.png)

Is there any logs i can find on my computer to give you or any other information that would be useful?

**Comment by CodyNguyen235** [comment]
I can confirm that the discord token is now working and I can have Kenku-fm join different channels i have him in, It appears to be unable to output any sound. The green circle around the bot in discord to indicate sound is permanently on despite no sound coming out. Sound does come out when the output is selected to "This Computer."
![image](https://user-images.githubusercontent.com/65568860/226769854-eee2637a-e800-4ad5-b0e0-c79c6b5ee511.png)
![image](https://user-images.githubusercontent.com/65568860/226769883-bb870880-7703-4652-ac36-673da913d422.png)

**Comment by CodyNguyen235** [comment]
Restarting my computer appears to have fixed the issue. Kenku-fm is working as intended in 1.3.1-test.

**Comment by nthouliss** [comment]
@CodyNguyen235 Thanks! We've published a full version v1.3.1 which you might want to download. It's better than the quick dev build that I gave you for 1.3.1-test 😄 

https://github.com/owlbear-rodeo/kenku-fm/releases/tag/v1.3.1

**Comment by CodyNguyen235** [comment]
@nthouliss Thank you for your work. I know its stressful but I know the community really appreciates you.
