### ISSUE TITLE
[Bug] Kenku connects but doesn't stream to a discord channel

### ISSUE THREAD

**Issue by DemoBytom** [owlbear-rodeo/kenku-fm#78]
Since at least yesterday Kenku just doesn't stream to Discord. It shows up in the channel, but stays mute. When switching channels I get `Error connecting to voice channel: Disconnected`

![image](https://user-images.githubusercontent.com/17877724/226648471-7bbf9e75-da00-4a46-a090-3555ecc101cb.png)

I tried downgrading to earlier version, reinstalling the app, cleaning windows firewall rules. Tested on two different discord servers.

The progress bar still moves as if it was playing, but stays silent.

Local play works no problem.

Currently running v1.2.4

**Comment by DemoBytom** [comment]
Ok, nevermind, the newly released 1.3.0 seems to have fixed the issue. I didn't notice there was a new release, and app didn't auto update on my end.

**Comment by QaisQaisQais** [comment]
where do i find the new release?
